# Generated by Django 2.1.7 on 2019-03-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_shareaccount_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type', models.CharField(max_length=4)),
                ('number', models.PositiveIntegerField()),
                ('account', models.CharField(max_length=256)),
            ],
        ),
    ]
