# Generated by Django 2.1.7 on 2019-06-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_sharedelete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareDelete',
        ),
        migrations.AddField(
            model_name='sharebuy',
            name='delete_status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='sharesell',
            name='delete_status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', editable=False, max_length=5),
        ),
    ]
