# Generated by Django 2.2.10 on 2024-02-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_auto_20190928_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharebuy',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='sharesell',
            options={'ordering': ('-date_created',)},
        ),
    ]
