# Generated by Django 2.2.10 on 2024-02-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0007_auto_20240207_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharebuy',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='shares.ShareAccount'),
        ),
        migrations.AlterField(
            model_name='sharesell',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='shares.ShareAccount'),
        ),
    ]
