# Generated by Django 2.1.7 on 2019-03-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_savingdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingdelete',
            name='tran_type',
            field=models.CharField(max_length=10),
        ),
    ]
