# Generated by Django 2.1.7 on 2019-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_auto_20190323_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingDelete',
        ),
        migrations.AddField(
            model_name='savingdeposit',
            name='delete_status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='savingwithdrawal',
            name='delete_status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', editable=False, max_length=5),
        ),
    ]
