# Generated by Django 2.2.10 on 2024-01-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0009_auto_20190928_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingaccount',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='savingdeposit',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='savingwithdrawal',
            options={'ordering': ('-date_created',)},
        ),
    ]
