# Generated by Django 2.2.10 on 2024-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_auto_20240121_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingwithdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
