# Generated by Django 2.2.10 on 2024-02-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0011_auto_20240208_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingdeposit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='savings.SavingAccount'),
        ),
        migrations.AlterField(
            model_name='savingwithdrawal',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='savings.SavingAccount'),
        ),
    ]
