# Generated by Django 2.1.7 on 2019-03-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanissue_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='status',
            field=models.CharField(choices=[('Deactivated', 'Deactivated'), ('Activated', 'Activated')], default='Deactivated', max_length=11),
        ),
    ]
