# Generated by Django 2.1.7 on 2019-03-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanaccount_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type', models.CharField(max_length=10)),
                ('principal', models.PositiveIntegerField()),
                ('loan_num', models.CharField(max_length=256)),
                ('account', models.CharField(max_length=256)),
            ],
        ),
    ]
