# Generated by Django 2.1.7 on 2019-03-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_savingdelete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavingDelete',
            new_name='LoanDelete',
        ),
    ]
