# Generated by Django 2.1.7 on 2019-08-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20190612_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoansIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_num', models.CharField(max_length=255, unique=True)),
                ('principal', models.PositiveIntegerField()),
                ('delete_status', models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', editable=False, max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.LoanAccount')),
            ],
            options={
                'verbose_name_plural': 'Loans issued',
            },
        ),
    ]
