# Generated by Django 2.2.10 on 2024-02-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_auto_20190928_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanissue',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='loanpayment',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='loansissue',
            options={'ordering': ('-date_created',), 'verbose_name_plural': 'Loans issued'},
        ),
    ]
