# Generated by Django 2.1.7 on 2019-06-12 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190606_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
