# Generated by Django 2.1.7 on 2019-09-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190612_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mem_number',
            field=models.CharField(default='', editable=False, max_length=50, unique=True),
        ),
    ]
