# Generated by Django 2.2.10 on 2020-05-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190928_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mem_number',
            field=models.PositiveIntegerField(default=0, editable=False, unique=True),
        ),
    ]
