# Generated by Django 2.2.10 on 2024-01-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200526_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
