# Generated by Django 2.2.10 on 2024-02-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20240126_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contact',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='member',
            name='kin1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kin1_set', to='members.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='kin2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kin2_set', to='members.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_no',
            field=models.CharField(default='+123', max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='proposed_monthly_contributions',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Residential Address'),
        ),
    ]
