# Generated by Django 2.2.10 on 2024-02-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20240207_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('-date_created',)},
        ),
    ]
