# Generated by Django 2.2.10 on 2024-02-11 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20240212_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('date_created',)},
        ),
    ]
