# Generated by Django 2.2.10 on 2024-01-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-date_created',)},
        ),
    ]
